### ISSUE TITLE
How to Change Tool Window Active Color

### ISSUE THREAD

**Issue by AmitBhatnagar24** [austinstanding/midnight-lights-vstheme#3]
Love this theme, but I can't use it as a daily driver because I find that the light blue that is being used to show the active tab / tool window (i.e.: solution explorer, etc.) is too bright and I can't read the window/tab title.  See picture with the red arrows pointing to the color I am speaking about. 

Is there any way to modify this color after the theme is applied? I tried changing colors of items in Tools -> Options -> Fonts and Colors but I can't figure out which item to tweak. 

![image](https://user-images.githubusercontent.com/8731921/137551667-8e17c120-2d0d-465f-b440-8355f9ee36bb.png)

**Comment by austinstanding** [comment]
Hey Amit, thanks for reaching out! Unfortunately there isn't a way to change these colors outside of the theme itself. Recently in VS 2022 Preview 4 a feature was released to allow for [color-coded document tabs](https://devblogs.microsoft.com/visualstudio/visual-studio-2022-preview-4-is-now-available/), but that won't really meet the need here.

I share your feelings that the light blue used doesn't give sufficient contrast. I changed displays from the one I used during the original development of this theme and would like to see this improved. I've been hesitant to make any significant changes without getting feedback from the many users of the theme, but I think this is a good opportunity to do so now.

I want to alter light blue to #03A7A3, which feels like a good balance between the original (#00D2CB) and it's secondary counterpart (#067B7A).

Here is a quick mockup I've photoshopped to show the before and after side-by-side.

![contrast_test](https://user-images.githubusercontent.com/22038786/137592447-f1e4751b-2c36-4b2c-bb8a-ebbdd412a83d.png)

I'll be working on this as I have time, and I'll respond here once I have the changes published.
