### ISSUE TITLE
ARM64 Support

### ISSUE THREAD

**Issue by drxjason** [austinstanding/midnight-lights-vstheme#4]
Hi, i am running visual studio 2022 on arm64. i would love to see an arm64 version of this theme. thanks

**Comment by austinstanding** [comment]
Hi @drxjason , you should now see arm64 support available on the [Midnight Lights marketplace page](https://marketplace.visualstudio.com/items?itemName=AustinStanding.vsthememidnightlights). Thanks for bringing that to my attention!

**Comment by drxjason** [comment]
literally thank you!!! i was trying to find a theme for my arch but there were none.. :)
